function(getting_started_sam_e51_cnano_sam_e51_cnano_assemble_rule target)
    set(inputVar "${ASSEMBLER_PRE};-g;-mprocessor=ATSAME51J20A;-Wa,--defsym=__MPLAB_BUILD=1,${MP_EXTRA_AS_POST};${MDFP_PATH}")
    string(REGEX REPLACE "[,]+" "," noDoubleCommas "${inputVar}")
    string(REGEX REPLACE ",$" "" noDanglingCommas "${noDoubleCommas}")
    target_compile_options(${target} PRIVATE "${noDanglingCommas}")
endfunction()
function(getting_started_sam_e51_cnano_sam_e51_cnano_assembleWithPreprocess_rule target)
    set(inputVar "${MP_EXTRA_AS_PRE};-g;-mprocessor=ATSAME51J20A;-DXPRJ_sam_e51_cnano=sam_e51_cnano;-Wa,--defsym=__MPLAB_BUILD=1,${MP_EXTRA_AS_POST}")
    string(REGEX REPLACE "[,]+" "," noDoubleCommas "${inputVar}")
    string(REGEX REPLACE ",$" "" noDanglingCommas "${noDoubleCommas}")
    target_compile_options(${target} PRIVATE "${noDanglingCommas}")
endfunction()
function(getting_started_sam_e51_cnano_sam_e51_cnano_compile_rule target)
    set(inputVar "${CC_PRE};-g;-x;c;-c;-mprocessor=ATSAME51J20A;-ffunction-sections;-fdata-sections;-O1;-fno-common;-Werror;-Wall;${INSTRUMENTED_TRACE_OPTIONS};${FUNCTION_LEVEL_PROFILING_OPTIONS};-DXPRJ_sam_e51_cnano=sam_e51_cnano;${MDFP_PATH};${CMSIS_PACK_INCLUDE}")
    string(REGEX REPLACE "[,]+" "," noDoubleCommas "${inputVar}")
    string(REGEX REPLACE ",$" "" noDanglingCommas "${noDoubleCommas}")
    target_compile_options(${target} PRIVATE "${noDanglingCommas}")
    target_include_directories(${target} PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}/../../../firmware/src;${CMAKE_CURRENT_SOURCE_DIR}/../../../firmware/src/config/sam_e51_cnano;${CMAKE_CURRENT_SOURCE_DIR}/../../../firmware/src/packs/ATSAME51J20A_DFP;${CMAKE_CURRENT_SOURCE_DIR}/../../../firmware/src/packs/CMSIS;${CMAKE_CURRENT_SOURCE_DIR}/../../../firmware/src/packs/CMSIS/CMSIS/Core/Include")
endfunction()
function(getting_started_sam_e51_cnano_sam_e51_cnano_compile_cpp_rule target)
    set(inputVar "${CC_PRE};-g;-mprocessor=ATSAME51J20A;-frtti;-fexceptions;-fno-check-new;-fenforce-eh-specs;-ffunction-sections;-O1;-fno-common;${INSTRUMENTED_TRACE_OPTIONS};${FUNCTION_LEVEL_PROFILING_OPTIONS};-DXPRJ_sam_e51_cnano=sam_e51_cnano;${MDFP_PATH};${CMSIS_PACK_INCLUDE}")
    string(REGEX REPLACE "[,]+" "," noDoubleCommas "${inputVar}")
    string(REGEX REPLACE ",$" "" noDanglingCommas "${noDoubleCommas}")
    target_compile_options(${target} PRIVATE "${noDanglingCommas}")
    target_include_directories(${target} PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}/../../../firmware/src;${CMAKE_CURRENT_SOURCE_DIR}/../../../firmware/src/config/sam_e51_cnano;${CMAKE_CURRENT_SOURCE_DIR}/../../../firmware/src/packs/ATSAME51J20A_DFP;${CMAKE_CURRENT_SOURCE_DIR}/../../../firmware/src/packs/CMSIS;${CMAKE_CURRENT_SOURCE_DIR}/../../../firmware/src/packs/CMSIS/CMSIS/Core/Include")
endfunction()
function(getting_started_sam_e51_cnano_sam_e51_cnano_link_rule target)
    set(inputVar "${MP_EXTRA_LD_PRE};-g;-mprocessor=ATSAME51J20A;-mno-device-startup-code;${INSTRUMENTED_TRACE_OPTIONS};${FUNCTION_LEVEL_PROFILING_OPTIONS};-DXPRJ_sam_e51_cnano=sam_e51_cnano;-Wl,--defsym=__MPLAB_BUILD=1,${MP_EXTRA_LD_POST},--script=${getting_started_sam_e51_cnano_sam_e51_cnano_LINKER_SCRIPT},,--defsym=_min_heap_size=512,,--memorysummary,memoryfile.xml;${MDFP_PATH}")
    string(REGEX REPLACE "[,]+" "," noDoubleCommas "${inputVar}")
    string(REGEX REPLACE ",$" "" noDanglingCommas "${noDoubleCommas}")
    target_link_options(${target} PRIVATE "${noDanglingCommas}")
endfunction()
